/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Command: npx gltfjsx@6.5.0 react.glb -T
    Author: xenadus (https://sketchfab.com/xenadus)
    License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
    Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
*/

import { Float, useGLTF } from '@react-three/drei';

const GitHubLogo = (props) => {
    const { nodes, materials } = useGLTF('/models/github.glb');

    return (
        <Float floatIntensity={1}>
            <group {...props} dispose={null}>
                <group
                    position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={35}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Curve021.geometry}
                        material={materials['glossy putih']}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Curve021_1.geometry}
                        material={materials.github}
                    />
                </group>
            </group>
        </Float>
    );
};

useGLTF.preload('/models/github.glb');

export default GitHubLogo;