/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import {useRef} from "react";

const Laptop = (props) => {
    const laptopRef = useRef();
    const { nodes, materials } = useGLTF('/models/laptop.glb')
    return (
        <group {...props} ref={laptopRef} dispose={null} scale={0.3}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.laptop.geometry}
                material={materials.palette}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.laptop001.geometry}
                material={materials['palette.001']}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.laptop002.geometry}
                material={materials['palette.002']}
                rotation={[Math.PI / 2, 0, 0]}
            />
        </group>
    )
}

useGLTF.preload('/models/laptop.glb')

export default Laptop;